version: '3'

services:

  algod:
    container_name: "algorand-sandbox-algod"
    build:
      context: ./
      dockerfile: ./images/algod/Dockerfile
      args:
        CHANNEL: "stable"
        URL: ""
        BRANCH: ""
        SHA: ""
        BOOTSTRAP_URL: ""
        GENESIS_FILE: "/tmp/images/algod/dev-genesis.json"
        TEMPLATE: "/tmp/images/algod/dev-template.json"
        TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        ALGOD_PORT: "4001"
        KMD_PORT: "4002"
        CDT_PORT: "9392"
    ports:
      - 4001:4001
      - 4002:4002
      - 9392:9392
    volumes:
      - ./:/shared:z

  indexer:
    container_name: "algorand-sandbox-indexer"
    build:
      context: ./
      dockerfile: ./images/indexer/Dockerfile
      args:
        URL: "https://github.com/algorand/indexer"
        BRANCH: "master"
        SHA: ""
    ports:
      - 8980:8980
    restart: unless-stopped
    environment:
      URL: "https://github.com/algorand/indexer"
      BRANCH: "master"
      SHA: ""
      DISABLED: ""
      PORT: "8980"
      SNAPSHOT: ""
      CONNECTION_STRING: "host=indexer-db port=5432 user=algorand password=algorand dbname=indexer_db sslmode=disable"
      ALGOD_ADDR: "algod:4001"
      ALGOD_TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    volumes:
      - ./:/shared:z

  indexer-db:
    image: "postgres:13-alpine"
    container_name: "algorand-sandbox-postgres"
    ports:
      - 5433:5432
    user: postgres
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer_db

  